apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - literals:
      - altGreeting=Good Morning!
      - enableRisky="false"
    name: the-map
labels:
  - includeSelectors: true
    pairs:
      app: hello
