apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
commonAnnotations:
  note: Hello, I am staging!
resources:
  - ../../base
patches:
  - path: map.yaml
labels:
  - includeSelectors: true
    pairs:
      org: acmeCorporation
      variant: staging
