apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
nameSuffix: -v1
configMapGenerator:
  - behavior: merge
    files:
      - plumbing.properties
      - secret.properties
    name: my-configmap
