apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
patches:
  - path: ingress_patch.json
    target:
      group: networking.k8s.io
      kind: Ingress
      name: my-ingress
      version: v1beta1
