apiVersion: v1
data:
  db.conf: |
    endpoint=127.0.0.1:1234
    name=app
    user=admin
    pass=/var/run/secrets/db/dbpass.txt
  ldap.conf: |
    endpoint=ldap://ldap.example.com
    bindDN=cn=admin,dc=example,dc=com
    pass=/var/run/secrets/ldap/ldappass.txt
  main.conf: '| color=cornflower_blue log_level=info'
kind: ConfigMap
metadata:
  name: conf-kb969b4c4f
---
apiVersion: v1
data:
  dbpass.txt: |
    fi93b3JrL2NvZGUvZ29fY29kZS9rdXN0b21pemUvbGVhcm4va3VzdG9taXplX2NvbXBvbm
    VudHMvY29tcG9uZW50cy9leHRlcm5hbF9kYi9kYnBhc3MudHh0
kind: Secret
metadata:
  name: dbpass-77fc6gd4h4
type: Opaque
---
apiVersion: v1
data:
  ldappass.txt: |
    fi93b3JrL2NvZGUvZ29fY29kZS9rdXN0b21pemUvbGVhcm4va3VzdG9taXplX2NvbXBvbm
    VudHMvY29tcG9uZW50cy9sZGFwL2xkYXBwYXNzLnR4dA==
kind: Secret
metadata:
  name: ldappass-ccdhmf4552
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /var/run/secrets/ldap/
          name: ldappass
        - mountPath: /var/run/secrets/db/
          name: dbpass
        - mountPath: /etc/config
          name: conf
      volumes:
      - name: ldappass
        secret:
          secretName: ldappass-ccdhmf4552
      - name: dbpass
        secret:
          secretName: dbpass-77fc6gd4h4
      - configMap:
          name: conf-kb969b4c4f
        name: conf
